version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nikolai
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: thirdfort